<<<<<<< HEAD
# Generated by Django 3.2.5 on 2022-05-20 08:22
=======
# Generated by Django 3.2.5 on 2022-05-20 07:21
>>>>>>> 87b7cea19dade998ec53a17252fda2ce5807ca9a

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cookrecipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe', models.CharField(max_length=100)),
                ('ingredient', models.CharField(max_length=255)),
            ],
        ),
    ]
