# Generated by Django 3.2.5 on 2022-05-20 02:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe2', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cookrecipe',
            old_name='name',
            new_name='recipe',
        ),
    ]
