# Generated by Django 3.2.5 on 2022-05-23 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe2', '0002_auto_20220523_1155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.URLField(default='', max_length=255),
        ),
    ]
