# Generated by Django 3.2.5 on 2022-05-23 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe2', '0003_alter_recipe_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipe',
            options={'managed': False},
        ),
    ]
