# Generated by Django 3.2.5 on 2022-05-23 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe2', '0004_alter_recipe_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='recipe',
            table='recipe',
        ),
    ]
