# Generated by Django 3.2.5 on 2022-05-20 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Add',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Add_stock', models.CharField(max_length=10, null=True)),
                ('Add_amount', models.CharField(max_length=4, null=True)),
                ('Add_month', models.CharField(max_length=20, null=True)),
            ],
            options={
                'db_table': 'Add',
            },
        ),
        migrations.CreateModel(
            name='stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_name', models.CharField(max_length=10)),
                ('stock_amount', models.CharField(max_length=20)),
                ('distance', models.FloatField()),
                ('time_info', models.CharField(max_length=10)),
                ('start_end_info', models.CharField(max_length=30)),
                ('cre_date', models.DateField()),
            ],
            options={
                'db_table': 'stock',
            },
        ),
    ]
