# Generated by Django 3.2.5 on 2022-05-19 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add',
            name='expiration_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
