# Generated by Django 3.2.5 on 2022-05-19 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stockapp', '0002_alter_add_expiration_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='add',
            name='expiration_date',
        ),
        migrations.RemoveField(
            model_name='add',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='add',
            name='user_name',
        ),
    ]
