# Generated by Django 3.2.5 on 2022-05-19 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockapp', '0003_auto_20220519_1543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add',
            name='amount',
            field=models.IntegerField(max_length=4),
        ),
    ]
