# Generated by Django 3.2.5 on 2022-05-20 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockapp', '0005_alter_add_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_name', models.CharField(max_length=10)),
                ('stock_amount', models.CharField(max_length=20)),
                ('distance', models.FloatField()),
                ('time_info', models.CharField(max_length=10)),
                ('start_end_info', models.CharField(max_length=30)),
                ('cre_date', models.DateField()),
            ],
            options={
                'db_table': 'stock',
                'managed': False,
            },
        ),
        migrations.RenameField(
            model_name='add',
            old_name='amount',
            new_name='Add_amount',
        ),
        migrations.RenameField(
            model_name='add',
            old_name='stock',
            new_name='Add_stock',
        ),
    ]
